development:
  adapter: postgresql
  encoding: unicode
  database: flashcards_development
  pool: 5
  timeout: 5000
  username: root1
  password: gfhjkm12

test:
  adapter: postgresql
  encoding: unicode
  database: flashcards_test
  pool: 5
  timeout: 5000
  username: root1
  password: gfhjkm12
